### ISSUE TITLE
Couldn't install mtllm through requirements.txt file

### ISSUE THREAD

**Issue by thushalya** [Jaseci-Labs/mtllm#3]
![image](https://github.com/Jaseci-Labs/mtllm/assets/89528929/6d3d4ed2-bacf-4847-82a9-1b84bb5e36ba)

I tried to install mtllm through my requirements.txt file but it says there is a version conflict between jaclang and mtllm

**Comment by chandralegend** [comment]
It seems liket required  you have a dependacy that requires strict `jaclang==0.5.1.8` but newest mtllm requires `jaclang >= 0.7.5`. So unless the `jaclang-jaseci` has a version that supports the newest `jaclang` you wont be able to use `mtllm`. Please reach out to the maintainers of `jaclang-jaseci` or use `jaclang==0.5.17` (which might have the mtllm inbuilt)

If so use the `import:py from jaclang.core.llms, <model_provider>` instead of `import:py from mtllm.llms, <model_provider>`.
